// 코드 오류를 수정하기 위한 데이터입니다.
// S : serum, U : urine
module.exports = {
    // 코드 통합
    "edate3": "edate",
    "glu_fbs": "glu0",
    "plt": "plat",
    "wbc_b": "wbc",
    "rbc_b": "rbc",
    "uricacid_b": "uricacid",
    "fvcbest": 'fvc',
    "fev1best": "fev1",
    "fef25best": "fef25",

    // 09-10 코드 오류 수정
    "alb(s)": "albumin",
    "alb(s)_ctc": "albumin",
    "alt(s)": "alt",
    "alt(s)_ctc": "alt",
    "alts": "alt",
    "ast(s)": "ast",
    "ast(s)_ctc": "ast",
    "asts": "ast",
    "b/c ratio": "",
    "b/c ratio_ctc": "",
    "bcratio": "",
    "bun(s)": "bun",
    "bun(s)_ctc": "bun",
    "buns": "bun",
    "bacteria": "",
    "bilirubin": "t_bil",
    "blood": "",
    "casts": "",
    "color": "",
    "creatinine(ru)": "creatine_u",
    "creatinine(s)": "creatine",
    "creatinine(s)_ctc": "creatine",
    "creatinineru": "creatine_u",
    "creatinines": "creatine",
    "crystals": "",
    "dna extraction": "",
    "dnaextraction": "",
    "e.p cells": "",
    "e.pcells": "",
    "glu-fbs(naf)": "glu_fbs",
    "glu-fbs(naf)_ctc": "glu_fbs",
    "glufbsnaf": "glu_fbs",
    "glucose": "glu0",
    "s.g": "glu0",
    "hdl chol": "hdl",
    "hdl-chol_유전체": "hdl",
    "hdlchol": "hdl",
    "hba1c": "hba1c",
    "hba1c_유전체": "hba1c",
    "hematocrit": "hct",
    "hematocrit_유전체": "hct",
    "hemoglobin": "hb",
    "hemoglobin_유전체": "hb",
    "insulin(ria)": "insul_fbs",
    "insulinria": "insul_fbs",
    "ketone": "u_ket",
    "ldl chole_유전체": "ldl",
    "ldl chole": "ldl",
    "ldlchole": "ldl",
    "leptin": "",
    "mch": "mch",
    "mchc": "mchc",
    "mchc-유전체": "mchc",
    "mch_유전체": "mch",
    "mcv": "mcv",
    "mcv_유전체": "mcv",
    "microal./crtn ratio": "",
    "microal.crtnratio": "",
    "microalbumin (ru)": "",
    "microalbumin(ru)": "",
    "microalbuminru": "",
    "nitrite": "",
    "other": "",
    "plasma분리": "",
    "platelet": "plat",
    "platelet_유전체": "plat",
    "protein": "bodyprt",
    "protein(s)": "bodyprt",
    "protein(s)_ctc": "bodyprt",
    "proteins": "bodyprt",
    "rbc": "rbc",
    "rbc_u": "",
    "rbc_유전체": "rbc",
    "serum분리": "",
    "t.bili(s)": "t_bil",
    "t.bili(s)_ctc": "t_bil",
    "t.bilis": "t_bil",
    "t.chol": "tchl",
    "t.chol_유전체": "tchl",
    "t.cholesterol": "tchl",
    "tg(s)": "tg",
    "tg(s)_유전체": "tg",
    "tgs": "tg",
    "u.a(s)": "uricacid",
    "u.a(s)_ctc": "uricacid",
    "u.as": "uricacid",
    "urobilinogen": "u_uro",
    "wbc": "wbc",
    "wbc_u": "wbc_u",
    "wbc_유전체": "wbc",
    "ph": "u_ph",
    "r-gtp(s)": "r_gtp",
    "r-gtp(s)_ctc": "r_gtp",
    "rgtps": "r_gtp",
    "albumins": "albumin"
}


// const fs = require('fs');
// let data = String(fs.readFileSync('./결측치.csv', { encoding: 'utf-8' }))
// let keys = new Set(data.split('\r\n').map(e => e.split(',')).flat().filter(e => !e.match(/F\d+|S\d+/)).filter(e => e))
// let keys = Array(...new Set(Object.keys(module.exports)))
// console.log(JSON.stringify(Object.fromEntries(keys.map((k) => [k.toLowerCase(), module.exports[k]])), null, 4))
